baseURL: "http://alidorludovic.github.io"
languageCode: "en-us"
title: Ludovic Alidor
theme: "hugo-tania"
pagination:
  pagerSize: 6
copyright: Everything is mine
disqusShortname: https-hugo-tania-netlify-app

params:
  # Emoji will show before the blog title on site navbar.
  titleEmoji: 🧉

  # Logo will show before the blog title on site navbar.
  titleLogo: 
  
  # Enable float footnotes.
  # Default to true
  enableFootnotes: true
  
  siteName: "Ludovic ALIDOR"
  siteDesc: "Ludovic ALIDOR's website"
  author: "Ludovic ALIDOR"

  colorScheme:
    # Enable toggle colorScheme
    # Default to true
    toggle: true
    # Default colorScheme
    # Default to auto
    default: auto

  # Limit how many categories filter show above search input.
  # Default to 5
  maxCategoryToShow: 10

  # Show your socail information with icon on index bio with `_index.md` content.
  socialOptions:
    dev-to:
    email: alidorludovic@gmail.com
    facebook:
    github: https://github.com/alidorludovic
    instagram: https://www.instagram.com/ludovic.alidor/
    linkedin: https://www.linkedin.com/in/ludovic-alidor-00703a140/
    medium:
    stack-overflow:
    steam:
    telegram: https://t.me/alidorludovic
    threads: https://www.threads.net/@ludovic.alidor
    twitter: https://x.com/ludovic_alidor
    twitch:
    whatsapp: https://wa.me/262692176764
    
    #mastodon: https://www.youtube.com/watch?v=dQw4w9WgXcQ

  faro_analytics:
    endpoint: "https://faro-collector-prod-us-east-0.grafana.net/collect/0a90369b35edb0efcfe6205cdd4b2a14"
    name: "alidorludovic.github.io"
    version: "1.0.0"
    #environnement: "production"
    analyze: true

  # Comments settings
  comments:
    enabled: true
    provider: giscus

    giscus:
      repo: WingLim/hugo-tania
      id: "${{ secrets.GISCUS_ID }}"
      category:
        name: Comments
        id: "${{ secrets.GISCUS_CATEGORY_ID }}"

        

menu:
  header:
    - name: Articles
      url: "/articles/"
    - name: About 
      url: "/aboutme/"
    - name: Résumé
      url : "https://drive.google.com/file/d/1gJv8djpfX1gb3DApjUBzdH122KgrGt7i/view?usp=sharing"
  footer:
    - name : Ludovic Alidor © 2022 
#    - name: RSS
#      url: "/index.xml"

markup:
  highlight:
    noClasses: false
    lineNos: true
  goldmark:
    renderer:
      unsafe: true
module:
  imports:
    - path: faro-analytics

outputs:
  home: ["HTML", "RSS", "JSON"]